### ISSUE TITLE
Setting up ExpressJS env, make basic routing

### ISSUE THREAD

**Issue by 0xEbrahim** [0xEbrahim/Natours-API#1]
Need to setup express environment, and add esliner & prettier configurations.. and write the basic routing for the application

**Comment by mustafa-cpu-pr** [comment]
Basic Routes configuration template for express:
const express = require('express');
const app = express();

// Middleware
app.use(express.json());

// Basic routes
app.get('/', (req, res) => {
  res.send('Welcome to Express!');
});

app.get('/about', (req, res) => {
  res.send('About Page');
});

app.post('/data', (req, res) => {
  res.json({ message: 'Data received', data: req.body });
});

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
